[package]
name = "rye"
version = "0.1.0"
authors = ["Taylor Gordon <taylorgordon@fb.com>"]
edition = "2018"

[dependencies]
image = "0.21.2"
lazy_static = "1.3.0"
ndarray = "0.12.1"
ndarray-linalg = "0.10.0"
rand = "0.6.5"
rayon = "1.0.3"